### ISSUE TITLE
App crashes after putting wii iso in rom folder and/or main app folder

### ISSUE THREAD

**Issue by newhacker1746** [WilliamLCobb/GC4iOS#11]
I have compiled the latest today using a Yosemite 10.10.5 iMac and xcode 7.2.1, direct to a pangu jailbroken 6+ running 9.1. After adding the jit fix to that cpp, starfield would work and run (5fps!) However, when I added a (scrubbed) Super Mario Galaxy 1 iso around 1.4gb in size (yes, I ripped using my OWN wii, and my OWN copy!) to the rom folder, the app crashes after around 5 seconds. Running ./Dolphin from terminal results in an abort trap: 6 error. Whether the iso is in the rom folder, main app folder, or both, the same crash happens. When the iso is removed, the app starts normally. The iso is a pal edition that can run at pal60. 16gb 9.1 jailbroken iphone 6 plus

**Comment by newhacker1746** [comment]
Im sorry. That other one was a miss sent issue

**Comment by jakeb072001** [comment]
Dolphin for iOS is nowhere near done.
You will have to wait for the next update.

**Comment by MaquinaDelMisterio** [comment]
Many things are missing here, it might take sometime before we can play games without crashing in my case, for example. Non jailbroken iPad Pro. We have to remember that William is doing this alone, we have to give him time. im sure its lot of work.

**Comment by newhacker1746** [comment]
Yeah, it is a lot of work. I'll be patient until the next update.
