### ISSUE TITLE
Unable to add ROMs to GC4iOS

### ISSUE THREAD

**Issue by ajfarino2** [WilliamLCobb/GC4iOS#12]
When adding iso files to my device through a files app or simply through a Safari download, ROMs will not add to the app in any way possible.

**Comment by dreamboyn81** [comment]
/var/mobile/Documents/Dolphin/
![image](https://cloud.githubusercontent.com/assets/15012771/15980486/92812778-2f9e-11e6-80fd-f257d5d39263.png)

**Comment by WilliamLCobb** [comment]
Yep. This will be moved to /var/mobile/Documents/GC4iOS in the next update. Support for downloading roms will return, though I think most of the decompression libraries I've been using have trouble opening the 1.4 GB roms
