### ISSUE TITLE
ipad air 2 dolphin emulator

### ISSUE THREAD

**Issue by zakusa** [WilliamLCobb/GC4iOS#19]
hi i have question i have ipad air 2 ios 9.3.2 and once jailbreak is released im going to test wii emulator but do you guys know if ipad air 2 will be able to play mario galaxy at full speed once emulator is done

i have a i3 4130, gtx 960, and 8gb ram computer and mario galaxy laggs sometimes so ya i dont think mario galaxy will be able to run full speed on ipad air 2 after seeing a8x vs i3 4130 in cpuboss but does anyone know if its possible to

a8x vs i3 4130:
http://cpuboss.com/cpus/Intel-Core-i3-4130-vs-Apple-A8X

**Comment by WilliamLCobb** [comment]
No. It will be a few years before Mario Galaxy will run full speed
