### ISSUE TITLE
Fixing JIT

### ISSUE THREAD

**Issue by WilliamLCobb** [WilliamLCobb/GC4iOS#2]
Currently the JIT recompiler is working amazingly. The problem is iOS's code signing is going to be hard to work around. Usually pages used for JIT are protected to allow reading, writing, and executing. iOS only allows mapping read and write pages. With a workaround/hack, we can enable read and write pages. However, it is impossible, even with a jailbreak, to map read, write, and execute pages now.

This means we have to change the protection on a page every time the emulator reads or writes to it. This wasn't too hard to implement on iNDS, but Dolphin makes it much harder by modifying the JIT code while running. I think I'll be able to get it to work but the overhead from protecting pages twice for every JIT operation will probably slow down the emulator quite a bit.

Someone suggested we mmap a memory region twice with 2 sets of protections, but I don't believe this is possible on iOS.

If anyone has any other ideas about how to fix this, that would be cool.

**Comment by nfsvsgta** [comment]
Like I said permission can be changed on ifile. Idos and play! WEre unable to load games so when I changed permissions of the Roms through ifile and allowed read write execute etc. I think if we do that for all the files of the emu through ifile it may help. Don't know whether it will be that easy but is worth a shot. What do u think?

**Comment by ghost** [comment]
I'd wait until IOS 10 beta comes out in a couple weeks. It would be a shame if you put a lot of hard work into this and ended up not being able to run it on newer versions.

**Comment by DarknesGaming** [comment]
I agree with @pmp174. We should wait for iOS 10 (or iOS X) beta to be released.
The JIT recompiler is most likely using the ARM architecture, and not i386 or sparc. Did you build it using arm-apple-darwin? Maybe iOS will allow that, unless Apple made a JIT recompiler and shoved it into a kit that needs to be added to an Xcode project.
I'm just trying to be helpful.

**Comment by DarknesGaming** [comment]
iOS 10 Beta has been released last week. And I have some information that might help, and it came from a friend who's also a programmer.
Even if JIT does work on an Apple device, you have to find a way to make JIT bypass its own sandbox and run on the memory heap. The heap should be where the root processes are, and whatever is on the heap is what the device will run, right?

**Comment by DarknesGaming** [comment]
Pangu just released a jailbreak for iOS 9.2-9.3.3. You can get their tool from their official site tomorrow for the English version, or go to taig9.com for Pangu's Chinese tool.
Just because 25PP helped make the tool doesn't mean the tool is complete trash. People have tried it wihout experiencing problems.

**Comment by WilliamLCobb** [comment]
JIT already works
