### ISSUE TITLE
How to install roms onto GC4IOS

### ISSUE THREAD

**Issue by XCalibruh** [WilliamLCobb/GC4iOS#25]
I was able to install the app onto my iPad through Xcode but when i use documents 5 to download super mario sunshine and open with GC4IOS. I get a white screen with the controls. I am using a non jailbroken device. iPad air running iOS 9.3.3. How can i add roms through xcode as file sharing is turned off so itunes doesnt work. Please help i am really looking forward to using this app

**Comment by Multipixelone** [comment]
I used iFunBox to add roms, but only got wind waker to successfully ONCE. But I got a rom added!

**Comment by XCalibruh** [comment]
how?????? Ifunbox sandbox is disabled

**Comment by GingerOfOz** [comment]
Try using iExplorer.  It's a handy tool that works for me.

**Comment by Multipixelone** [comment]
I just clicked show all apps, but iExplorer works well too.

**Comment by ghost** [comment]
Download the app File Hub on your iOS device (lite version works too) and on the list on the left, tap "Wifi Transfer". Download the file on your computer then go to the IP address file hub shows. On that website, click "Upload files". Select the file and then wait for it to upload to the device. Once done, press "Stop" inside the File Hub app and then hold down on the ROM until you see a list. Tap "Open in..." and select GC4iOS. Wait for it to import into GC4iOS and then you're done.
