### ISSUE TITLE
SaveStates and Load Save Files

### ISSUE THREAD

**Issue by brand175** [WilliamLCobb/GC4iOS#29]
Will Dolphin SaveStates or in-game SaveStates be supported anytime soon?

**Comment by GingerOfOz** [comment]
They already are! I personally have tested the GC mem-card file from my computer, and it loaded up my data without a hitch.  To do so, put it in the var/mobile/library/GC on your iDevice.  Save states go in the var/mobile/library/savestates.  I am unsure if you are able to load them through the emulator currently, but I'll see if I can find a way.  If there is, then I might be able to get around most load screens crashing and test the actual game...

**Comment by GingerOfOz** [comment]
I tried a few things, but I wasn't able to find any way to load the save states. Mem-card still works just fine though.
