### ISSUE TITLE
GameCube games crash after selecting them.

### ISSUE THREAD

**Issue by Fadi5555** [WilliamLCobb/GC4iOS#3]
@WilliamLCobb hi there.
As it mentioned above the currently build of dolphin emu is crashing after selecting roms.
Any idea please?

**Comment by pmp174** [comment]
This emulator is still not complete or tested on all devices. I recommend you post your device specs and version so that he knows what devices are having trouble.

**Comment by jakeb072001** [comment]
This is in very early alpha so nothing will work just yet.

**Comment by nfsvsgta** [comment]
Yep it crashes on my iPhone 6 as well. Hopefully it does not have anything to do with ram. Y don't u try it on ur iPad. If it ran on it means the problem is ram.

**Comment by Fadi5555** [comment]
Unfortunately my iPad Air 2 is not jailbroken (iOS 9.3.1)
It it does I'll test on it and tell you my result.
I guess there is is something missing to start running. But as the guys said it's still in beta stage.
The best part is @WilliamLCobb is trying to improve it quickly. Maybe next few days it goes very well because dolphin itself is very old project and he tried to port it on iOS as a platform. So we should hope to enable JIT as well as OpenGL render. If goes well it gonna be pretty cool. And games should run very good.

**Comment by nfsvsgta** [comment]
Well I hope it's not the ram. Any way bout to download nfs carbon

**Comment by jakeb072001** [comment]
It's deffinetly not the ram, ram does not cause crashing all it does is slow down.
It will only crash because of ram on older devices

**Comment by WilliamLCobb** [comment]
It definitely crashes because of ram. It crashes for me pretty often if I don't close all of my apps because of no ram. Once I reduce the memory requirement it should fix the crashes. I doubt it will run on anything besides the 6s or any other device with 2GB of ram

**Comment by Fadi5555** [comment]
I'm waiting for jailbreak to could test it on my iPad Air 2.
Again I hope the new jailbreak will come with JIT support. To make the work becomes more easier.

**Comment by jakeb072001** [comment]
Really? Usually 1GB ram difference doesn't crash apps.
I can even use multitasking on my iPad Air at a fast speed.
I'm not a developer so I wouldn't really know.

**Comment by minelegend1** [comment]
I'm anxious to see how it might do with my iPad Pro with 4GB of RAM. However, I definitely agree that this app is in a very early state and that it's not optimized to really run on other devices besides the iPhone 6S and possibly the iPad Pro models.

**Comment by nfsvsgta** [comment]
That's strange then. Nfs carbon does not crash. Instead it stays on a black screen. ????

**Comment by nfsvsgta** [comment]
On iPhone 6

**Comment by nfsvsgta** [comment]
Wait now that I set the permissions it crashes

**Comment by nfsvsgta** [comment]
@WilliamLCobb how's the jit? And any chance for devices with lower than 2 gb ram

**Comment by jakeb072001** [comment]
How long do you think it will be until this works on slightly older devices (iPad Air)?
I really want to play some luigis mansion and zelda.

**Comment by WilliamLCobb** [comment]
I think I fixed the crashing issue. Let me know if you guys are able to boot any games

**Comment by WilliamLCobb** [comment]
1GB devices should work fine, I was wrong about the lack of ram

**Comment by jakeb072001** [comment]
Now it doesn't crash!
But now there's just a black screen...
It could be lag or the emulation doesn't work just yet.
I tried luigis mansion, starfield and button tracer.

**Comment by MaquinaDelMisterio** [comment]
OMG, this is wonderful. Im going to report how it goes on my iPad pro 13¨ that has 4gb ram, maybe that helps.

**Comment by WilliamLCobb** [comment]
@MaquinaDelMisterio Awesome. When I run dolphin on my Mac on cached interpreter, I get similar speeds to my iPhone which is really promising. Hopefully JIT will speedup Dolphin on iOS as much as it does on OSX

**Comment by MaquinaDelMisterio** [comment]
Im sure it will. At least some playable speed.

**Comment by MaquinaDelMisterio** [comment]
William, could you please help me? When i run the project it fails when building, any idea why is this happening?

**Comment by nfsvsgta** [comment]
Hi. Now the games stay on a black screen.  Both starfield.dol and animal crossing. Can u look into them pls. Thanks

**Comment by WilliamLCobb** [comment]
Please post you device and iOS version when reporting bugs

**Comment by Fadi5555** [comment]
About me I have same issue of black screen.
iPhone 5s iOS 8.4 jailbroken (with JIT enable functionality by TaiG jailbreak)

**Comment by MaquinaDelMisterio** [comment]
Okey, iPad Pro 13" iOS 9.3.1, i got 2 to 5 fps. Also, when i disconnect my iPad from xcode the app crashes luigis mansion, but also cant load the demo rom. It runs only when connected to it.

**Comment by nfsvsgta** [comment]
iPhone 6 iOS 8.1. Black screen

**Comment by MaquinaDelMisterio** [comment]
Tried another rom, with the iPad Pro on iOS 9.3.1 and it has a blackscreen, Xcode error log: error: memory read failed for 0x0. (EXC_BAD_ACCESS code=1, adress=0x0

**Comment by Nmzik** [comment]
> Xcode error log: error: memory read failed for 0x0. (EXC_BAD_ACCESS code=1, adress=0x0
I had the same issue. You need to mark this page as executable to be able to run it. See Issue #5

**Comment by WilliamLCobb** [comment]
Games may still randomly crash when launching, but should work after reopening the app.
