### ISSUE TITLE
DolphiniOS will not compile - al.h file not found

### ISSUE THREAD

**Issue by ajfarino2** [WilliamLCobb/GC4iOS#8]
Hello,

When trying to compile DolphiniOS in Xcode after checking it out via source control, I cannot compile the app due to the error "al.h file not found". I have made sure time and time again that the scheme is Dolphin and the output is my iOS device (which is the iPad Pro and definitely not 32 bit w/ more than 1GB of RAM).

**Comment by MaquinaDelMisterio** [comment]
did you tried to compile it directly to the idevice, or tried firt on the simulator. I have had a lot of different errors, when trying to compile the app. What worked for me is download the file to my desktop, and open the xcode project, connect my device and run it directly into it, no simulator.

**Comment by ajfarino2** [comment]
I have already tried doing so, does not work for me.

**Comment by MaquinaDelMisterio** [comment]
Okey, try and try again. Close completely xcode, erease the donwloaded files, every file. Download it again, open xcode file dont change anything, just your bundle identifier and run it directly to your device.

**Comment by ajfarino2** [comment]
I have also done that a dozen times, does not work as well.

**Comment by MaquinaDelMisterio** [comment]
This is weird. Try tomorrow, maybe its going to be a new one avaiable.

**Comment by MaquinaDelMisterio** [comment]
Im trying the latest one, let me see what happens.

**Comment by MaquinaDelMisterio** [comment]
Its working for me. I don't understand whats the problem with your files. 

<img width="1280" alt="captura de pantalla 2016-06-03 a las 7 53 50 p m" src="https://cloud.githubusercontent.com/assets/4268943/15796547/23170e72-29c5-11e6-82c2-75d73da18258.png">

**Comment by MaquinaDelMisterio** [comment]
@minelegend1 Try to paste the file on: externals-OpenAL-Include
https://www.dropbox.com/s/mzdea45zzlxjp3v/al.h?dl=0

**Comment by WilliamLCobb** [comment]
My other dolphin repository has better build instructions. You can try using that

**Comment by ajfarino2** [comment]
@WilliamLCobb Where would that other dolphin repo be located?

**Comment by MaquinaDelMisterio** [comment]
@minelegend1 https://github.com/WilliamLCobb/dolphin

**Comment by dreamboyn81** [comment]
Don't have a MAC, please update the deb file.

**Comment by DJRuckASS** [comment]
@WilliamLCobb could you please update the cydia repo thanks

**Comment by WilliamLCobb** [comment]
This should be fixed with the new source
