### ISSUE TITLE
Dolphin on iPhone 6 ios 8.1

### ISSUE THREAD

**Issue by nfsvsgta** [WilliamLCobb/GC4iOS#9]
Just a post for the status of dolphin emulator on iPhone 6 iOS 8.1 with jit broken and all. Current status is that it stays on black screen. Hope to see it fixed in next update. I'll update the status on next update hopefully with a video/screen of commercial game running

**Comment by nfsvsgta** [comment]
Starfield.dol
![image](https://cloud.githubusercontent.com/assets/19260668/15804380/acb89398-2b1f-11e6-888e-57fbfd0e7d30.jpg)
On iPhone 6 iOS 8.1

**Comment by MaquinaDelMisterio** [comment]
What you can do to fix black screen is to download the Xcode project and paste this on MemArena.cpp

You have to change a line that is like this one but with out |MAP_JIT|, find it and use this one instead: void\* base = mmap(0, MemSize, PROT_READ | PROT_WRITE, MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0); This will fix Jit on jailbroken devices.

**Comment by nfsvsgta** [comment]
If only I had a Mac. Thanks anyway :)

**Comment by MaquinaDelMisterio** [comment]
You welcome. As a suggestion, you can try Virtualmachine. ;)

**Comment by WilliamLCobb** [comment]
Should be fixed for GameCube games. JIT does not currently work and Wii emulation will not be focused on. Wii games may work but they will be really slow, even with JIT, and I won't be adding any wii specific fixes
